name: Host

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  make-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test host application
        working-directory: app/cat-guardian
        run: make check
